### ISSUE TITLE
ngrading: Supports Photoshop LUT format.

### ISSUE THREAD

**Issue by MikuAuahDark** [MikuAuahDark/NPad93#5]
Photoshop has function to export to "Color Lookup Tables" and it has various options. I think supporting this in ngrading is great.

**Comment by flamendless** [comment]
I think my artist did export from PS as well and that's what we're using in the game 🤔 I'll confirm 

Yup. We use exported LUT from PS

**Comment by MikuAuahDark** [comment]
I don't think I'll be supporting this, but patches welcome.
