### ISSUE TITLE
Example on how to use NWFC ?

### ISSUE THREAD

**Issue by halsten-dev** [MikuAuahDark/NPad93#8]
Hi, 

I have lot of trouble using NWFC. Can you add an example to understand how to use it? 

Thanks a lot :)

**Comment by MikuAuahDark** [comment]
Hmm, I think NWFC needs some revisit and documentation. NWFC was an attempt
to rewrite it from the original C# implementation 1:1. It's magnitude
slower than the original C# implementation too.

**Comment by halsten-dev** [comment]
Alright that's pretty sad :) 

I was hoping to be able to test it out. 

Of course it's slower than C#, I was prepared for that. 😄 

Thanks for your answer.
